"""Research operating boundaries for the Axiom kernel.

The package root is intentionally lazy.  Importing one protocol module must
not execute every governance, Portfolio, source, and trial implementation as a
hidden part of that module's scientific implementation closure.  Public names
remain source-compatible and are loaded only when callers request them.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any


_PUBLIC_MODULE_BY_NAME = {
    "ArchitectureChassisSpec": "chassis",
    "ArchitectureContinuationDirection": "governance",
    "ArchitectureContinuationMode": "governance",
    "ArchitectureReview": "governance",
    "ArchitectureReviewConclusion": "governance",
    "ArchitectureRole": "chassis",
    "ArchitectureRoleSpec": "chassis",
    "BatchSpec": "portfolio",
    "BatchSpecError": "portfolio",
    "CandidateBinding": "sources",
    "CandidateSourceBinding": "sources",
    "ChassisIdentityError": "chassis",
    "ComponentParityDimension": "chassis",
    "ComponentParityEvidence": "chassis",
    "ControlledStudyChassis": "chassis",
    "ConcurrentFamilyEvaluationMode": "portfolio",
    "ConcurrentFamilyManifest": "portfolio",
    "DecisionBasisRecord": "portfolio",
    "DecisionKind": "portfolio",
    "DecisionLens": "portfolio",
    "DecisionLensAssessment": "portfolio",
    "DecisionLensPosition": "portfolio",
    "DecisionOption": "portfolio",
    "DiagnosisConfidence": "governance",
    "EvidenceState": "governance",
    "InferenceDependency": "sources",
    "InferenceDependencyKind": "sources",
    "MaterialReference": "trials",
    "MissionResearchIntake": "governance",
    "NegativeMemory": "trials",
    "ObservationAssessment": "sources",
    "PortfolioAction": "portfolio",
    "PortfolioAxis": "portfolio",
    "PortfolioDecision": "portfolio",
    "PortfolioDecisionError": "portfolio",
    "PortfolioSnapshot": "portfolio",
    "QuantTeamDecisionReview": "portfolio",
    "REQUIRED_INTAKE_SURFACES": "governance",
    "RecertificationResult": "sources",
    "RuntimeObservation": "sources",
    "RuntimeObservationState": "sources",
    "ResearchGovernanceError": "governance",
    "ResearchLayer": "governance",
    "SemanticWarning": "trials",
    "SemanticQuestionCore": "semantic_question",
    "SemanticQuestionEquivalenceProposal": "semantic_question",
    "SemanticQuestionError": "semantic_question",
    "SemanticQuestionLineageProposal": "semantic_question",
    "SemanticQuestionRelation": "semantic_question",
    "SleeveDependencySpec": "sources",
    "SleeveRuntimeDecision": "sources",
    "SleeveSpec": "sources",
    "SourceAction": "sources",
    "SourceContract": "sources",
    "SourceContractError": "sources",
    "SourceEligibility": "sources",
    "SourceEligibilityError": "sources",
    "SourceEligibilityReceipt": "sources",
    "SourceEligibilityState": "sources",
    "SourceFailureKind": "sources",
    "SourceTransitionEvidence": "sources",
    "SourceType": "sources",
    "StopRuleState": "study_continuation",
    "StudyContinuationDecision": "study_continuation",
    "StudyContinuationError": "study_continuation",
    "StudyContinuationOutcome": "study_continuation",
    "StudyDiagnosis": "governance",
    "StudyTrialContext": "trials",
    "TrialAccountant": "trials",
    "TrialAccountingError": "trials",
    "TrialDecision": "trials",
    "architecture_component_semantic_surface_identity": "chassis",
    "architecture_family_identity": "chassis",
    "assess_observation": "sources",
    "bind_candidate_source": "sources",
    "component_domain": "chassis",
    "component_semantic_surface_identity": "chassis",
    "diagnosis_branch": "governance",
    "evaluate_sleeves": "sources",
    "executable_semantic_surface_identity": "chassis",
    "normalize_architecture_payload": "chassis",
    "recertify_source": "sources",
    "require_combinable_chassis": "chassis",
    "validate_controlled_executable": "chassis",
}

__all__ = [
    "ArchitectureChassisSpec",
    "ArchitectureContinuationDirection",
    "ArchitectureContinuationMode",
    "ArchitectureReview",
    "ArchitectureReviewConclusion",
    "ArchitectureRole",
    "ArchitectureRoleSpec",
    "BatchSpec",
    "BatchSpecError",
    "CandidateBinding",
    "CandidateSourceBinding",
    "ChassisIdentityError",
    "ComponentParityDimension",
    "ComponentParityEvidence",
    "ControlledStudyChassis",
    "ConcurrentFamilyEvaluationMode",
    "ConcurrentFamilyManifest",
    "DecisionBasisRecord",
    "DecisionKind",
    "DecisionLens",
    "DecisionLensAssessment",
    "DecisionLensPosition",
    "DecisionOption",
    "DiagnosisConfidence",
    "EvidenceState",
    "InferenceDependency",
    "InferenceDependencyKind",
    "MaterialReference",
    "MissionResearchIntake",
    "NegativeMemory",
    "ObservationAssessment",
    "PortfolioAction",
    "PortfolioAxis",
    "PortfolioDecision",
    "PortfolioDecisionError",
    "PortfolioSnapshot",
    "QuantTeamDecisionReview",
    "REQUIRED_INTAKE_SURFACES",
    "RecertificationResult",
    "RuntimeObservation",
    "RuntimeObservationState",
    "ResearchGovernanceError",
    "ResearchLayer",
    "SemanticWarning",
    "SemanticQuestionCore",
    "SemanticQuestionEquivalenceProposal",
    "SemanticQuestionError",
    "SemanticQuestionLineageProposal",
    "SemanticQuestionRelation",
    "SleeveDependencySpec",
    "SleeveRuntimeDecision",
    "SleeveSpec",
    "SourceAction",
    "SourceContract",
    "SourceContractError",
    "SourceEligibility",
    "SourceEligibilityError",
    "SourceEligibilityReceipt",
    "SourceEligibilityState",
    "SourceFailureKind",
    "SourceTransitionEvidence",
    "SourceType",
    "StudyTrialContext",
    "StudyDiagnosis",
    "StopRuleState",
    "StudyContinuationDecision",
    "StudyContinuationError",
    "StudyContinuationOutcome",
    "TrialAccountant",
    "TrialAccountingError",
    "TrialDecision",
    "assess_observation",
    "architecture_component_semantic_surface_identity",
    "architecture_family_identity",
    "bind_candidate_source",
    "component_domain",
    "component_semantic_surface_identity",
    "diagnosis_branch",
    "evaluate_sleeves",
    "executable_semantic_surface_identity",
    "normalize_architecture_payload",
    "recertify_source",
    "require_combinable_chassis",
    "validate_controlled_executable",
]

if set(__all__) != set(_PUBLIC_MODULE_BY_NAME):
    raise RuntimeError("research public lazy import registry drifted")


def __getattr__(name: str) -> Any:
    module_name = _PUBLIC_MODULE_BY_NAME.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(f"{__name__}.{module_name}"), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *__all__})
